### PR TITLE
Minor refactor of SCSS file structure

### PR DESCRIPTION
**Pull request by Aqcurate**
From now on, only edit the SCSS. Do not modify the CSS directly please.

You have two options to transform the SCSS to CSS.

1. $ sass scss/styles.scss css/styles.css
2. $ sass --watch scss:css

The first method manually processes the scss file. The second method listens to any changes in the scss directory, and automatically updates styles.css.

Personally, I recommend trying to get the second method set up. It's super helpful. (I'm not sure if anyone else will have this problem, but I had to downgrade to get listen to work.)

$ sudo gem uninstall listen -v 1.0.3
$ sudo gem install listen -v 0.7.3

If gem isn't working properly, run these commands:

$ sudo apt-add-repository ppa:brightbox/ruby-ng
$ sudo apt-get update
$ sudo apt-get install ruby2.4
$ sudo apt-get install ruby-dev

Otherwise, make sure everything is solid.

### CODE REVIEW

**Comment by Aqcurate** [comment]
Also, to download sass, either run:

$ sudo apt-get install ruby-sass

or

$ sudo gem install sass

Check you have it using:

$ sass -v

**Comment by otakaran** [comment]
Sounds good. Why are we moving font files into the root directory? @Stan-sst @EscapingGithub

**Comment by staslyakhov** [comment]
It seems like common practice nowadays to have images/ and fonts/ as separate directories in root @otakar-sst. Though I am sure that these things will be refactored many time over until we are satisfied.

**Comment by otakaran** [comment]
Yes, I can see the logic behind that. Everything looks good to me.

**Review by otakaran — APPROVED** [review]

**Comment by Aqcurate** [comment]
Looks good to me.

**Pull request merged**
